---
title: "p8105_hw2_LCA2149"
output: github_document
date: "2025-09-23"
---

## Question 1

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import the pols-month dataset and break the variable mon into integer variables year, month, and day; replace month number with month name; create a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable.
```{r}
polsmonth_df=
  read_csv("data/pols-month.csv") |>
  separate(
    mon, into = c ("year", "month", "day"), sep = "-") |>
      mutate(
        year = as.integer(year),
        month = month.name[as.integer(month)],
        day=as.integer(day),
        president = case_when (
          prez_gop == 1 ~ "gop",
          prez_dem == 1 ~ "dem"
        )
      ) |>
      select(-prez_dem, -prez_gop, -day)
```

Now let's import snp.csv clean it up.
```{r}
snp_df=
  read_csv("data/snp.csv") |>
      mutate(
        date=mdy(date),
        year = year(date),
        month = month.name[month(date)] 
      ) |>
  select(year, month, everything(), -date) |>
  arrange(year, match(month, month.name))
```

Now let's import unemployment.csv and clean it up.
```{r}
unemployment_df=
  read_csv("data/unemployment.csv") |>
  pivot_longer(
    cols = -Year,               
    names_to = "month",         
    values_to = "unemployment"  
  ) |>
  mutate(
 month = str_to_title(month)
  ) |>
  arrange(Year, month)
```


